version: 2
project_name: dcm-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: dcm
    main: ./cmd/dcm
    binary: dcm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    
  - id: install
    main: ./cmd/install
    binary: install
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: uninstall
    main: ./cmd/uninstall
    binary: uninstall
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: full
    ids: [dcm, install, uninstall]
    strip_binary_directory: false
    formats: [ 'zip' ]
    name_template: '{{ .ProjectName }}_full_{{ .Os }}_{{ .Arch }}_{{ .Version }}'

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  github:
    owner: Disneyjr
    name: dcm-cli